# Generated by Django 2.1.1 on 2018-10-15 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='月報時間', max_length=100)),
                ('company_id', models.CharField(help_text='公司代號', max_length=100)),
                ('company_name', models.CharField(help_text='公司名稱', max_length=100)),
                ('now_month', models.CharField(help_text='當月營收', max_length=100)),
                ('last_month', models.CharField(help_text='上月營收', max_length=100)),
                ('last_year_now_month', models.CharField(help_text='前年當月營收', max_length=100)),
                ('last_month_contrast', models.CharField(help_text='上月比較增減', max_length=100)),
                ('last_year_now_month_contrast', models.CharField(help_text='去年同月增減', max_length=100)),
                ('now_month_total', models.CharField(help_text='當月累計營收', max_length=100)),
                ('last_year_total', models.CharField(help_text='去年累計營收', max_length=100)),
                ('prophase_contrast', models.CharField(help_text='前期比較增減', max_length=100)),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='月報時間', max_length=100)),
                ('stock_id', models.CharField(help_text='證券代號', max_length=100)),
                ('stock_name', models.CharField(help_text='證券名稱', max_length=100)),
                ('deal_stock_num', models.CharField(help_text='成交股數', max_length=100)),
                ('deal_num', models.CharField(help_text='成交筆數', max_length=100)),
                ('deal_amount', models.CharField(help_text='成交金額', max_length=100)),
                ('open', models.CharField(help_text='開盤價', max_length=100)),
                ('high', models.CharField(help_text='最高價', max_length=100)),
                ('low', models.CharField(help_text='最低價', max_length=100)),
                ('close', models.CharField(help_text='收盤價', max_length=100)),
                ('spread', models.CharField(help_text='漲跌價差', max_length=100)),
                ('last_buy_price', models.CharField(help_text='最後揭示買價', max_length=100)),
                ('last_buy_num', models.CharField(help_text='最後揭示買量', max_length=100)),
                ('last_sell_price', models.CharField(help_text='最後揭示賣價', max_length=100)),
                ('last_sell_num', models.CharField(help_text='最後揭示賣量', max_length=100)),
                ('ratio', models.CharField(help_text='本益比', max_length=100)),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
